completed ticket 5
ElraSala14/nc-news pull request #3
Opened 2022-07-27 10:29 UTC by ElraSala14

Completed ticket 5 view topic with a list of related articles

2022-07-27 13:44 UTC, Poonam-raj requested changes
So this is looking really really good 🎉 

One thing I'd like you to action:
- Articles and Articlesbytopic are both almost identical components except for the fact one filters by topic. I'd like you to  combine these two so you can use ONE component for both the topic-filtered list of articles and the full list of articles, it's do-able but you might need some logic in the component 👀

^ when you've tried actioning that throw us a PR again

2022-07-27 13:44 UTC, Poonam-raj commented on src/components/Articlesbytopic.jsx
> +console.log(topic, '<----- topic params')
Get rid of the console logs and commented out code if you can before you do a PR :)

2022-07-27 13:44 UTC, Poonam-raj commented on src/components/Articlesbytopic.jsx
> +          <div className="articleName" key={article.article_id}>
If you want to use a <ul> tag you should be using <li> tags for each item in the list otherwise there will be errors in your console. If you don't want to do <li> you shouldn't be using a <ul> tag to wrap the content

2022-07-27 13:44 UTC, Poonam-raj commented on src/components/Navbar.jsx
>        <Link to="/">Home</Link>{"   "}
Ideally you shouldn't be relying on whitespace ({"     "}) to position your elements, you should be  using CSS to do this kind of styling when you do come to it

2022-07-28 10:00 UTC, Rayhaan2k9 approved these changes
Nice

2022-07-28 10:01 UTC, merged